name: market_invoices_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  printing:
  intl: ^0.19.0
  speech_to_text:
  dio:
  flutter_dotenv:
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - .env
    - shorebird.yaml
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700 
